[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
bkswap = "3Hy9MBHowHUmhmSP1KahEvvtC8e6DxzLGeFjuiBQwRUA"
raydium-clmm-router = "2WKs6hQg3cesC2D7Hxtt878beWFezbd5dJZmFmrXumnH"
bkswapv2 = "Fv3fcy7DJRNdQu5618oJ8FGe7LdQ7oWGUj5oVVxFweTv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/xxx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
