[features]
seeds = false
skip-lint = false

[programs.localnet]
bkswap = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
raydium_extra_router = "DGumNmyMhSeuNYsJLWD7VELLoENEenp99pTtDqSR9dUy"

[programs.devnet]
bkswap = "5oah7zWWknX7KjWHDZrca9f53HX5WxNUp3y9p6gJMyU3"
raydium_router = "2avzgAzGDza8BB4DRzVMhSus5FsyTux3Bqyo6Mrqto9T"
raydium_test_helper = "71Lq4vbeFA9eicHkADR1BX3Go9EvjRYY2vWoQQ89wf2z"
raydium_extra_router = "DGumNmyMhSeuNYsJLWD7VELLoENEenp99pTtDqSR9dUy"

[programs.mainnet]
bkswap = "3Hy9MBHowHUmhmSP1KahEvvtC8e6DxzLGeFjuiBQwRUA"
raydium_router = "4Ji3eRdwjCg2wuuJVbRBvqkPKz2xs4tchxQ4tZNhbUfs"
raydium_extra_router = "DGumNmyMhSeuNYsJLWD7VELLoENEenp99pTtDqSR9dUy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
# cluster = "Localnet"

wallet = "/Users/xp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --bail -t 1000000 tests/**/*.ts"
